// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for bind9 metrics.
type MetricsConfig struct {
	Bind9MemoryTotal                     MetricConfig `mapstructure:"bind9.memory.total"`
	Bind9MemoryUsage                     MetricConfig `mapstructure:"bind9.memory.usage"`
	Bind9NetworkSocketAccept             MetricConfig `mapstructure:"bind9.network.socket.accept"`
	Bind9NetworkSocketAcceptFailures     MetricConfig `mapstructure:"bind9.network.socket.accept.failures"`
	Bind9NetworkSocketActive             MetricConfig `mapstructure:"bind9.network.socket.active"`
	Bind9NetworkSocketBindFailures       MetricConfig `mapstructure:"bind9.network.socket.bind.failures"`
	Bind9NetworkSocketClosed             MetricConfig `mapstructure:"bind9.network.socket.closed"`
	Bind9NetworkSocketConnection         MetricConfig `mapstructure:"bind9.network.socket.connection"`
	Bind9NetworkSocketConnectionFailures MetricConfig `mapstructure:"bind9.network.socket.connection.failures"`
	Bind9NetworkSocketOpenFailures       MetricConfig `mapstructure:"bind9.network.socket.open.failures"`
	Bind9NetworkSocketOpened             MetricConfig `mapstructure:"bind9.network.socket.opened"`
	Bind9NetworkSocketReceiveErrors      MetricConfig `mapstructure:"bind9.network.socket.receive.errors"`
	Bind9NetworkSocketSendErrors         MetricConfig `mapstructure:"bind9.network.socket.send.errors"`
	Bind9NetworkTraffic                  MetricConfig `mapstructure:"bind9.network.traffic"`
	Bind9ResolverCacheEntries            MetricConfig `mapstructure:"bind9.resolver.cache.entries"`
	Bind9ResolverCacheHits               MetricConfig `mapstructure:"bind9.resolver.cache.hits"`
	Bind9ResolverCacheMisses             MetricConfig `mapstructure:"bind9.resolver.cache.misses"`
	Bind9ResolverQueries                 MetricConfig `mapstructure:"bind9.resolver.queries"`
	Bind9ResolverResponses               MetricConfig `mapstructure:"bind9.resolver.responses"`
	Bind9ResolverValidationAttempt       MetricConfig `mapstructure:"bind9.resolver.validation.attempt"`
	Bind9ResolverValidationSuccess       MetricConfig `mapstructure:"bind9.resolver.validation.success"`
	Bind9ServerQueries                   MetricConfig `mapstructure:"bind9.server.queries"`
	Bind9ServerResponses                 MetricConfig `mapstructure:"bind9.server.responses"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		Bind9MemoryTotal: MetricConfig{
			Enabled: true,
		},
		Bind9MemoryUsage: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketAccept: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketAcceptFailures: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketActive: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketBindFailures: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketClosed: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketConnection: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketConnectionFailures: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketOpenFailures: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketOpened: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketReceiveErrors: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkSocketSendErrors: MetricConfig{
			Enabled: true,
		},
		Bind9NetworkTraffic: MetricConfig{
			Enabled: true,
		},
		Bind9ResolverCacheEntries: MetricConfig{
			Enabled: true,
		},
		Bind9ResolverCacheHits: MetricConfig{
			Enabled: true,
		},
		Bind9ResolverCacheMisses: MetricConfig{
			Enabled: true,
		},
		Bind9ResolverQueries: MetricConfig{
			Enabled: true,
		},
		Bind9ResolverResponses: MetricConfig{
			Enabled: true,
		},
		Bind9ResolverValidationAttempt: MetricConfig{
			Enabled: true,
		},
		Bind9ResolverValidationSuccess: MetricConfig{
			Enabled: true,
		},
		Bind9ServerQueries: MetricConfig{
			Enabled: true,
		},
		Bind9ServerResponses: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for bind9 metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
