// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					Bind9MemoryTotal: MetricConfig{
						Enabled: true,
					},
					Bind9MemoryUsage: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketAccept: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketAcceptFailures: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketActive: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketBindFailures: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketClosed: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketConnection: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketConnectionFailures: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketOpenFailures: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketOpened: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketReceiveErrors: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkSocketSendErrors: MetricConfig{
						Enabled: true,
					},
					Bind9NetworkTraffic: MetricConfig{
						Enabled: true,
					},
					Bind9ResolverCacheEntries: MetricConfig{
						Enabled: true,
					},
					Bind9ResolverCacheHits: MetricConfig{
						Enabled: true,
					},
					Bind9ResolverCacheMisses: MetricConfig{
						Enabled: true,
					},
					Bind9ResolverQueries: MetricConfig{
						Enabled: true,
					},
					Bind9ResolverResponses: MetricConfig{
						Enabled: true,
					},
					Bind9ResolverValidationAttempt: MetricConfig{
						Enabled: true,
					},
					Bind9ResolverValidationSuccess: MetricConfig{
						Enabled: true,
					},
					Bind9ServerQueries: MetricConfig{
						Enabled: true,
					},
					Bind9ServerResponses: MetricConfig{
						Enabled: true,
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					Bind9MemoryTotal: MetricConfig{
						Enabled: false,
					},
					Bind9MemoryUsage: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketAccept: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketAcceptFailures: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketActive: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketBindFailures: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketClosed: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketConnection: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketConnectionFailures: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketOpenFailures: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketOpened: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketReceiveErrors: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkSocketSendErrors: MetricConfig{
						Enabled: false,
					},
					Bind9NetworkTraffic: MetricConfig{
						Enabled: false,
					},
					Bind9ResolverCacheEntries: MetricConfig{
						Enabled: false,
					},
					Bind9ResolverCacheHits: MetricConfig{
						Enabled: false,
					},
					Bind9ResolverCacheMisses: MetricConfig{
						Enabled: false,
					},
					Bind9ResolverQueries: MetricConfig{
						Enabled: false,
					},
					Bind9ResolverResponses: MetricConfig{
						Enabled: false,
					},
					Bind9ResolverValidationAttempt: MetricConfig{
						Enabled: false,
					},
					Bind9ResolverValidationSuccess: MetricConfig{
						Enabled: false,
					},
					Bind9ServerQueries: MetricConfig{
						Enabled: false,
					},
					Bind9ServerResponses: MetricConfig{
						Enabled: false,
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
