// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bind9")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/bind9receiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
