// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

// AttributeDNSMessageDirection specifies the value dns.message.direction attribute.
type AttributeDNSMessageDirection int

const (
	_ AttributeDNSMessageDirection = iota
	AttributeDNSMessageDirectionReceived
	AttributeDNSMessageDirectionSent
)

// String returns the string representation of the AttributeDNSMessageDirection.
func (av AttributeDNSMessageDirection) String() string {
	switch av {
	case AttributeDNSMessageDirectionReceived:
		return "received"
	case AttributeDNSMessageDirectionSent:
		return "sent"
	}
	return ""
}

// MapAttributeDNSMessageDirection is a helper map of string to AttributeDNSMessageDirection attribute value.
var MapAttributeDNSMessageDirection = map[string]AttributeDNSMessageDirection{
	"received": AttributeDNSMessageDirectionReceived,
	"sent":     AttributeDNSMessageDirectionSent,
}

// AttributeNetworkTransport specifies the value network.transport attribute.
type AttributeNetworkTransport int

const (
	_ AttributeNetworkTransport = iota
	AttributeNetworkTransportUdp
	AttributeNetworkTransportTcp
)

// String returns the string representation of the AttributeNetworkTransport.
func (av AttributeNetworkTransport) String() string {
	switch av {
	case AttributeNetworkTransportUdp:
		return "udp"
	case AttributeNetworkTransportTcp:
		return "tcp"
	}
	return ""
}

// MapAttributeNetworkTransport is a helper map of string to AttributeNetworkTransport attribute value.
var MapAttributeNetworkTransport = map[string]AttributeNetworkTransport{
	"udp": AttributeNetworkTransportUdp,
	"tcp": AttributeNetworkTransportTcp,
}

// AttributeNetworkType specifies the value network.type attribute.
type AttributeNetworkType int

const (
	_ AttributeNetworkType = iota
	AttributeNetworkTypeIpv4
	AttributeNetworkTypeIpv6
)

// String returns the string representation of the AttributeNetworkType.
func (av AttributeNetworkType) String() string {
	switch av {
	case AttributeNetworkTypeIpv4:
		return "ipv4"
	case AttributeNetworkTypeIpv6:
		return "ipv6"
	}
	return ""
}

// MapAttributeNetworkType is a helper map of string to AttributeNetworkType attribute value.
var MapAttributeNetworkType = map[string]AttributeNetworkType{
	"ipv4": AttributeNetworkTypeIpv4,
	"ipv6": AttributeNetworkTypeIpv6,
}

// AttributeOpcode specifies the value opcode attribute.
type AttributeOpcode int

const (
	_ AttributeOpcode = iota
	AttributeOpcodeQUERY
	AttributeOpcodeIQUERY
	AttributeOpcodeSTATUS
	AttributeOpcodeNOTIFY
	AttributeOpcodeUPDATE
)

// String returns the string representation of the AttributeOpcode.
func (av AttributeOpcode) String() string {
	switch av {
	case AttributeOpcodeQUERY:
		return "QUERY"
	case AttributeOpcodeIQUERY:
		return "IQUERY"
	case AttributeOpcodeSTATUS:
		return "STATUS"
	case AttributeOpcodeNOTIFY:
		return "NOTIFY"
	case AttributeOpcodeUPDATE:
		return "UPDATE"
	}
	return ""
}

// MapAttributeOpcode is a helper map of string to AttributeOpcode attribute value.
var MapAttributeOpcode = map[string]AttributeOpcode{
	"QUERY":  AttributeOpcodeQUERY,
	"IQUERY": AttributeOpcodeIQUERY,
	"STATUS": AttributeOpcodeSTATUS,
	"NOTIFY": AttributeOpcodeNOTIFY,
	"UPDATE": AttributeOpcodeUPDATE,
}

// AttributeRcode specifies the value rcode attribute.
type AttributeRcode int

const (
	_ AttributeRcode = iota
	AttributeRcodeNOERROR
	AttributeRcodeFORMERR
	AttributeRcodeSERVFAIL
	AttributeRcodeNXDOMAIN
	AttributeRcodeNOTIMP
	AttributeRcodeREFUSED
	AttributeRcodeYXDOMAIN
	AttributeRcodeYXRRSET
	AttributeRcodeNXRRSET
	AttributeRcodeNOTAUTH
	AttributeRcodeNOTZONE
	AttributeRcodeBADVERS
	AttributeRcodeBADCOOKIE
)

// String returns the string representation of the AttributeRcode.
func (av AttributeRcode) String() string {
	switch av {
	case AttributeRcodeNOERROR:
		return "NOERROR"
	case AttributeRcodeFORMERR:
		return "FORMERR"
	case AttributeRcodeSERVFAIL:
		return "SERVFAIL"
	case AttributeRcodeNXDOMAIN:
		return "NXDOMAIN"
	case AttributeRcodeNOTIMP:
		return "NOTIMP"
	case AttributeRcodeREFUSED:
		return "REFUSED"
	case AttributeRcodeYXDOMAIN:
		return "YXDOMAIN"
	case AttributeRcodeYXRRSET:
		return "YXRRSET"
	case AttributeRcodeNXRRSET:
		return "NXRRSET"
	case AttributeRcodeNOTAUTH:
		return "NOTAUTH"
	case AttributeRcodeNOTZONE:
		return "NOTZONE"
	case AttributeRcodeBADVERS:
		return "BADVERS"
	case AttributeRcodeBADCOOKIE:
		return "BADCOOKIE"
	}
	return ""
}

// MapAttributeRcode is a helper map of string to AttributeRcode attribute value.
var MapAttributeRcode = map[string]AttributeRcode{
	"NOERROR":   AttributeRcodeNOERROR,
	"FORMERR":   AttributeRcodeFORMERR,
	"SERVFAIL":  AttributeRcodeSERVFAIL,
	"NXDOMAIN":  AttributeRcodeNXDOMAIN,
	"NOTIMP":    AttributeRcodeNOTIMP,
	"REFUSED":   AttributeRcodeREFUSED,
	"YXDOMAIN":  AttributeRcodeYXDOMAIN,
	"YXRRSET":   AttributeRcodeYXRRSET,
	"NXRRSET":   AttributeRcodeNXRRSET,
	"NOTAUTH":   AttributeRcodeNOTAUTH,
	"NOTZONE":   AttributeRcodeNOTZONE,
	"BADVERS":   AttributeRcodeBADVERS,
	"BADCOOKIE": AttributeRcodeBADCOOKIE,
}

var MetricsInfo = metricsInfo{
	Bind9MemoryTotal: metricInfo{
		Name: "bind9.memory.total",
	},
	Bind9MemoryUsage: metricInfo{
		Name: "bind9.memory.usage",
	},
	Bind9NetworkSocketAccept: metricInfo{
		Name: "bind9.network.socket.accept",
	},
	Bind9NetworkSocketAcceptFailures: metricInfo{
		Name: "bind9.network.socket.accept.failures",
	},
	Bind9NetworkSocketActive: metricInfo{
		Name: "bind9.network.socket.active",
	},
	Bind9NetworkSocketBindFailures: metricInfo{
		Name: "bind9.network.socket.bind.failures",
	},
	Bind9NetworkSocketClosed: metricInfo{
		Name: "bind9.network.socket.closed",
	},
	Bind9NetworkSocketConnection: metricInfo{
		Name: "bind9.network.socket.connection",
	},
	Bind9NetworkSocketConnectionFailures: metricInfo{
		Name: "bind9.network.socket.connection.failures",
	},
	Bind9NetworkSocketOpenFailures: metricInfo{
		Name: "bind9.network.socket.open.failures",
	},
	Bind9NetworkSocketOpened: metricInfo{
		Name: "bind9.network.socket.opened",
	},
	Bind9NetworkSocketReceiveErrors: metricInfo{
		Name: "bind9.network.socket.receive.errors",
	},
	Bind9NetworkSocketSendErrors: metricInfo{
		Name: "bind9.network.socket.send.errors",
	},
	Bind9NetworkTraffic: metricInfo{
		Name: "bind9.network.traffic",
	},
	Bind9ResolverCacheEntries: metricInfo{
		Name: "bind9.resolver.cache.entries",
	},
	Bind9ResolverCacheHits: metricInfo{
		Name: "bind9.resolver.cache.hits",
	},
	Bind9ResolverCacheMisses: metricInfo{
		Name: "bind9.resolver.cache.misses",
	},
	Bind9ResolverQueries: metricInfo{
		Name: "bind9.resolver.queries",
	},
	Bind9ResolverResponses: metricInfo{
		Name: "bind9.resolver.responses",
	},
	Bind9ResolverValidationAttempt: metricInfo{
		Name: "bind9.resolver.validation.attempt",
	},
	Bind9ResolverValidationSuccess: metricInfo{
		Name: "bind9.resolver.validation.success",
	},
	Bind9ServerQueries: metricInfo{
		Name: "bind9.server.queries",
	},
	Bind9ServerResponses: metricInfo{
		Name: "bind9.server.responses",
	},
}

type metricsInfo struct {
	Bind9MemoryTotal                     metricInfo
	Bind9MemoryUsage                     metricInfo
	Bind9NetworkSocketAccept             metricInfo
	Bind9NetworkSocketAcceptFailures     metricInfo
	Bind9NetworkSocketActive             metricInfo
	Bind9NetworkSocketBindFailures       metricInfo
	Bind9NetworkSocketClosed             metricInfo
	Bind9NetworkSocketConnection         metricInfo
	Bind9NetworkSocketConnectionFailures metricInfo
	Bind9NetworkSocketOpenFailures       metricInfo
	Bind9NetworkSocketOpened             metricInfo
	Bind9NetworkSocketReceiveErrors      metricInfo
	Bind9NetworkSocketSendErrors         metricInfo
	Bind9NetworkTraffic                  metricInfo
	Bind9ResolverCacheEntries            metricInfo
	Bind9ResolverCacheHits               metricInfo
	Bind9ResolverCacheMisses             metricInfo
	Bind9ResolverQueries                 metricInfo
	Bind9ResolverResponses               metricInfo
	Bind9ResolverValidationAttempt       metricInfo
	Bind9ResolverValidationSuccess       metricInfo
	Bind9ServerQueries                   metricInfo
	Bind9ServerResponses                 metricInfo
}

type metricInfo struct {
	Name string
}

type metricBind9MemoryTotal struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.memory.total metric with initial data.
func (m *metricBind9MemoryTotal) init() {
	m.data.SetName("bind9.memory.total")
	m.data.SetDescription("Total memory allocated by context name")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9MemoryTotal) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, contextNameAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("context.name", contextNameAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9MemoryTotal) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9MemoryTotal) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9MemoryTotal(cfg MetricConfig) metricBind9MemoryTotal {
	m := metricBind9MemoryTotal{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9MemoryUsage struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.memory.usage metric with initial data.
func (m *metricBind9MemoryUsage) init() {
	m.data.SetName("bind9.memory.usage")
	m.data.SetDescription("Memory usage by context name")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9MemoryUsage) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, contextNameAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("context.name", contextNameAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9MemoryUsage) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9MemoryUsage) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9MemoryUsage(cfg MetricConfig) metricBind9MemoryUsage {
	m := metricBind9MemoryUsage{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketAccept struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.accept metric with initial data.
func (m *metricBind9NetworkSocketAccept) init() {
	m.data.SetName("bind9.network.socket.accept")
	m.data.SetDescription("Total number of socket accept calls, by socket statistic name")
	m.data.SetUnit("sockets")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketAccept) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketAccept) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketAccept) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketAccept(cfg MetricConfig) metricBind9NetworkSocketAccept {
	m := metricBind9NetworkSocketAccept{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketAcceptFailures struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.accept.failures metric with initial data.
func (m *metricBind9NetworkSocketAcceptFailures) init() {
	m.data.SetName("bind9.network.socket.accept.failures")
	m.data.SetDescription("Total number of socket accept failures, by socket statistic name")
	m.data.SetUnit("failures")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketAcceptFailures) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketAcceptFailures) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketAcceptFailures) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketAcceptFailures(cfg MetricConfig) metricBind9NetworkSocketAcceptFailures {
	m := metricBind9NetworkSocketAcceptFailures{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketActive struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.active metric with initial data.
func (m *metricBind9NetworkSocketActive) init() {
	m.data.SetName("bind9.network.socket.active")
	m.data.SetDescription("Number of currently active sockets, by socket statistic name")
	m.data.SetUnit("sockets")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketActive) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketActive) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketActive) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketActive(cfg MetricConfig) metricBind9NetworkSocketActive {
	m := metricBind9NetworkSocketActive{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketBindFailures struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.bind.failures metric with initial data.
func (m *metricBind9NetworkSocketBindFailures) init() {
	m.data.SetName("bind9.network.socket.bind.failures")
	m.data.SetDescription("Total number of socket bind failures, by socket statistic name")
	m.data.SetUnit("failures")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketBindFailures) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketBindFailures) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketBindFailures) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketBindFailures(cfg MetricConfig) metricBind9NetworkSocketBindFailures {
	m := metricBind9NetworkSocketBindFailures{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketClosed struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.closed metric with initial data.
func (m *metricBind9NetworkSocketClosed) init() {
	m.data.SetName("bind9.network.socket.closed")
	m.data.SetDescription("Total number of sockets closed, by socket statistic name")
	m.data.SetUnit("sockets")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketClosed) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketClosed) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketClosed) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketClosed(cfg MetricConfig) metricBind9NetworkSocketClosed {
	m := metricBind9NetworkSocketClosed{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketConnection struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.connection metric with initial data.
func (m *metricBind9NetworkSocketConnection) init() {
	m.data.SetName("bind9.network.socket.connection")
	m.data.SetDescription("Total number of socket connections established, by socket statistic name")
	m.data.SetUnit("sockets")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketConnection) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketConnection) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketConnection) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketConnection(cfg MetricConfig) metricBind9NetworkSocketConnection {
	m := metricBind9NetworkSocketConnection{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketConnectionFailures struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.connection.failures metric with initial data.
func (m *metricBind9NetworkSocketConnectionFailures) init() {
	m.data.SetName("bind9.network.socket.connection.failures")
	m.data.SetDescription("Total number of socket connection failures, by socket statistic name")
	m.data.SetUnit("failures")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketConnectionFailures) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketConnectionFailures) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketConnectionFailures) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketConnectionFailures(cfg MetricConfig) metricBind9NetworkSocketConnectionFailures {
	m := metricBind9NetworkSocketConnectionFailures{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketOpenFailures struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.open.failures metric with initial data.
func (m *metricBind9NetworkSocketOpenFailures) init() {
	m.data.SetName("bind9.network.socket.open.failures")
	m.data.SetDescription("Total number of socket open failures, by socket statistic name")
	m.data.SetUnit("failures")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketOpenFailures) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketOpenFailures) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketOpenFailures) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketOpenFailures(cfg MetricConfig) metricBind9NetworkSocketOpenFailures {
	m := metricBind9NetworkSocketOpenFailures{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketOpened struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.opened metric with initial data.
func (m *metricBind9NetworkSocketOpened) init() {
	m.data.SetName("bind9.network.socket.opened")
	m.data.SetDescription("Total number of sockets opened, by socket statistic name")
	m.data.SetUnit("sockets")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketOpened) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketOpened) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketOpened) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketOpened(cfg MetricConfig) metricBind9NetworkSocketOpened {
	m := metricBind9NetworkSocketOpened{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketReceiveErrors struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.receive.errors metric with initial data.
func (m *metricBind9NetworkSocketReceiveErrors) init() {
	m.data.SetName("bind9.network.socket.receive.errors")
	m.data.SetDescription("Total number of socket receive errors, by socket statistic name")
	m.data.SetUnit("errors")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketReceiveErrors) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketReceiveErrors) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketReceiveErrors) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketReceiveErrors(cfg MetricConfig) metricBind9NetworkSocketReceiveErrors {
	m := metricBind9NetworkSocketReceiveErrors{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkSocketSendErrors struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.socket.send.errors metric with initial data.
func (m *metricBind9NetworkSocketSendErrors) init() {
	m.data.SetName("bind9.network.socket.send.errors")
	m.data.SetDescription("Total number of socket send errors, by socket statistic name")
	m.data.SetUnit("errors")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkSocketSendErrors) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("socket.stat", socketStatAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkSocketSendErrors) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkSocketSendErrors) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkSocketSendErrors(cfg MetricConfig) metricBind9NetworkSocketSendErrors {
	m := metricBind9NetworkSocketSendErrors{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9NetworkTraffic struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.network.traffic metric with initial data.
func (m *metricBind9NetworkTraffic) init() {
	m.data.SetName("bind9.network.traffic")
	m.data.SetDescription("DNS message count by size bucket, protocol, direction, and IP version")
	m.data.SetUnit("messages")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9NetworkTraffic) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, networkTransportAttributeValue string, networkTypeAttributeValue string, dnsMessageDirectionAttributeValue string, dnsMessageSizeBucketAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("network.transport", networkTransportAttributeValue)
	dp.Attributes().PutStr("network.type", networkTypeAttributeValue)
	dp.Attributes().PutStr("dns.message.direction", dnsMessageDirectionAttributeValue)
	dp.Attributes().PutStr("dns.message.size.bucket", dnsMessageSizeBucketAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9NetworkTraffic) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9NetworkTraffic) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9NetworkTraffic(cfg MetricConfig) metricBind9NetworkTraffic {
	m := metricBind9NetworkTraffic{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9ResolverCacheEntries struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.resolver.cache.entries metric with initial data.
func (m *metricBind9ResolverCacheEntries) init() {
	m.data.SetName("bind9.resolver.cache.entries")
	m.data.SetDescription("Number of entries in the resolver cache, by view")
	m.data.SetUnit("entries")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9ResolverCacheEntries) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9ResolverCacheEntries) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9ResolverCacheEntries) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9ResolverCacheEntries(cfg MetricConfig) metricBind9ResolverCacheEntries {
	m := metricBind9ResolverCacheEntries{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9ResolverCacheHits struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.resolver.cache.hits metric with initial data.
func (m *metricBind9ResolverCacheHits) init() {
	m.data.SetName("bind9.resolver.cache.hits")
	m.data.SetDescription("Number of cache hits in the resolver, by view")
	m.data.SetUnit("hits")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9ResolverCacheHits) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9ResolverCacheHits) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9ResolverCacheHits) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9ResolverCacheHits(cfg MetricConfig) metricBind9ResolverCacheHits {
	m := metricBind9ResolverCacheHits{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9ResolverCacheMisses struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.resolver.cache.misses metric with initial data.
func (m *metricBind9ResolverCacheMisses) init() {
	m.data.SetName("bind9.resolver.cache.misses")
	m.data.SetDescription("Number of cache misses in the resolver, by view")
	m.data.SetUnit("misses")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9ResolverCacheMisses) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9ResolverCacheMisses) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9ResolverCacheMisses) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9ResolverCacheMisses(cfg MetricConfig) metricBind9ResolverCacheMisses {
	m := metricBind9ResolverCacheMisses{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9ResolverQueries struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.resolver.queries metric with initial data.
func (m *metricBind9ResolverQueries) init() {
	m.data.SetName("bind9.resolver.queries")
	m.data.SetDescription("Number of outgoing queries made by the resolver, by view and query type")
	m.data.SetUnit("queries")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9ResolverQueries) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, viewAttributeValue string, qtypeAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("view", viewAttributeValue)
	dp.Attributes().PutStr("qtype", qtypeAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9ResolverQueries) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9ResolverQueries) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9ResolverQueries(cfg MetricConfig) metricBind9ResolverQueries {
	m := metricBind9ResolverQueries{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9ResolverResponses struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.resolver.responses metric with initial data.
func (m *metricBind9ResolverResponses) init() {
	m.data.SetName("bind9.resolver.responses")
	m.data.SetDescription("Number of responses received by the resolver, by view")
	m.data.SetUnit("responses")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9ResolverResponses) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9ResolverResponses) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9ResolverResponses) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9ResolverResponses(cfg MetricConfig) metricBind9ResolverResponses {
	m := metricBind9ResolverResponses{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9ResolverValidationAttempt struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.resolver.validation.attempt metric with initial data.
func (m *metricBind9ResolverValidationAttempt) init() {
	m.data.SetName("bind9.resolver.validation.attempt")
	m.data.SetDescription("Number of DNSSEC validation attempts by the resolver, by view")
	m.data.SetUnit("validations")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9ResolverValidationAttempt) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9ResolverValidationAttempt) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9ResolverValidationAttempt) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9ResolverValidationAttempt(cfg MetricConfig) metricBind9ResolverValidationAttempt {
	m := metricBind9ResolverValidationAttempt{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9ResolverValidationSuccess struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.resolver.validation.success metric with initial data.
func (m *metricBind9ResolverValidationSuccess) init() {
	m.data.SetName("bind9.resolver.validation.success")
	m.data.SetDescription("Number of successful DNSSEC validations by the resolver, by view")
	m.data.SetUnit("validations")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9ResolverValidationSuccess) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9ResolverValidationSuccess) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9ResolverValidationSuccess) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9ResolverValidationSuccess(cfg MetricConfig) metricBind9ResolverValidationSuccess {
	m := metricBind9ResolverValidationSuccess{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9ServerQueries struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.server.queries metric with initial data.
func (m *metricBind9ServerQueries) init() {
	m.data.SetName("bind9.server.queries")
	m.data.SetDescription("Total number of queries received by the server, by opcode")
	m.data.SetUnit("queries")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9ServerQueries) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, opcodeAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("opcode", opcodeAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9ServerQueries) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9ServerQueries) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9ServerQueries(cfg MetricConfig) metricBind9ServerQueries {
	m := metricBind9ServerQueries{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricBind9ServerResponses struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills bind9.server.responses metric with initial data.
func (m *metricBind9ServerResponses) init() {
	m.data.SetName("bind9.server.responses")
	m.data.SetDescription("Total number of responses sent by the server, by rcode")
	m.data.SetUnit("responses")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricBind9ServerResponses) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, rcodeAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("rcode", rcodeAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricBind9ServerResponses) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricBind9ServerResponses) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricBind9ServerResponses(cfg MetricConfig) metricBind9ServerResponses {
	m := metricBind9ServerResponses{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                     MetricsBuilderConfig // config of the metrics builder.
	startTime                                  pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                            int                  // maximum observed number of metrics per resource.
	metricsBuffer                              pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                                  component.BuildInfo  // contains version information.
	metricBind9MemoryTotal                     metricBind9MemoryTotal
	metricBind9MemoryUsage                     metricBind9MemoryUsage
	metricBind9NetworkSocketAccept             metricBind9NetworkSocketAccept
	metricBind9NetworkSocketAcceptFailures     metricBind9NetworkSocketAcceptFailures
	metricBind9NetworkSocketActive             metricBind9NetworkSocketActive
	metricBind9NetworkSocketBindFailures       metricBind9NetworkSocketBindFailures
	metricBind9NetworkSocketClosed             metricBind9NetworkSocketClosed
	metricBind9NetworkSocketConnection         metricBind9NetworkSocketConnection
	metricBind9NetworkSocketConnectionFailures metricBind9NetworkSocketConnectionFailures
	metricBind9NetworkSocketOpenFailures       metricBind9NetworkSocketOpenFailures
	metricBind9NetworkSocketOpened             metricBind9NetworkSocketOpened
	metricBind9NetworkSocketReceiveErrors      metricBind9NetworkSocketReceiveErrors
	metricBind9NetworkSocketSendErrors         metricBind9NetworkSocketSendErrors
	metricBind9NetworkTraffic                  metricBind9NetworkTraffic
	metricBind9ResolverCacheEntries            metricBind9ResolverCacheEntries
	metricBind9ResolverCacheHits               metricBind9ResolverCacheHits
	metricBind9ResolverCacheMisses             metricBind9ResolverCacheMisses
	metricBind9ResolverQueries                 metricBind9ResolverQueries
	metricBind9ResolverResponses               metricBind9ResolverResponses
	metricBind9ResolverValidationAttempt       metricBind9ResolverValidationAttempt
	metricBind9ResolverValidationSuccess       metricBind9ResolverValidationSuccess
	metricBind9ServerQueries                   metricBind9ServerQueries
	metricBind9ServerResponses                 metricBind9ServerResponses
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                                     mbc,
		startTime:                                  pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                              pmetric.NewMetrics(),
		buildInfo:                                  settings.BuildInfo,
		metricBind9MemoryTotal:                     newMetricBind9MemoryTotal(mbc.Metrics.Bind9MemoryTotal),
		metricBind9MemoryUsage:                     newMetricBind9MemoryUsage(mbc.Metrics.Bind9MemoryUsage),
		metricBind9NetworkSocketAccept:             newMetricBind9NetworkSocketAccept(mbc.Metrics.Bind9NetworkSocketAccept),
		metricBind9NetworkSocketAcceptFailures:     newMetricBind9NetworkSocketAcceptFailures(mbc.Metrics.Bind9NetworkSocketAcceptFailures),
		metricBind9NetworkSocketActive:             newMetricBind9NetworkSocketActive(mbc.Metrics.Bind9NetworkSocketActive),
		metricBind9NetworkSocketBindFailures:       newMetricBind9NetworkSocketBindFailures(mbc.Metrics.Bind9NetworkSocketBindFailures),
		metricBind9NetworkSocketClosed:             newMetricBind9NetworkSocketClosed(mbc.Metrics.Bind9NetworkSocketClosed),
		metricBind9NetworkSocketConnection:         newMetricBind9NetworkSocketConnection(mbc.Metrics.Bind9NetworkSocketConnection),
		metricBind9NetworkSocketConnectionFailures: newMetricBind9NetworkSocketConnectionFailures(mbc.Metrics.Bind9NetworkSocketConnectionFailures),
		metricBind9NetworkSocketOpenFailures:       newMetricBind9NetworkSocketOpenFailures(mbc.Metrics.Bind9NetworkSocketOpenFailures),
		metricBind9NetworkSocketOpened:             newMetricBind9NetworkSocketOpened(mbc.Metrics.Bind9NetworkSocketOpened),
		metricBind9NetworkSocketReceiveErrors:      newMetricBind9NetworkSocketReceiveErrors(mbc.Metrics.Bind9NetworkSocketReceiveErrors),
		metricBind9NetworkSocketSendErrors:         newMetricBind9NetworkSocketSendErrors(mbc.Metrics.Bind9NetworkSocketSendErrors),
		metricBind9NetworkTraffic:                  newMetricBind9NetworkTraffic(mbc.Metrics.Bind9NetworkTraffic),
		metricBind9ResolverCacheEntries:            newMetricBind9ResolverCacheEntries(mbc.Metrics.Bind9ResolverCacheEntries),
		metricBind9ResolverCacheHits:               newMetricBind9ResolverCacheHits(mbc.Metrics.Bind9ResolverCacheHits),
		metricBind9ResolverCacheMisses:             newMetricBind9ResolverCacheMisses(mbc.Metrics.Bind9ResolverCacheMisses),
		metricBind9ResolverQueries:                 newMetricBind9ResolverQueries(mbc.Metrics.Bind9ResolverQueries),
		metricBind9ResolverResponses:               newMetricBind9ResolverResponses(mbc.Metrics.Bind9ResolverResponses),
		metricBind9ResolverValidationAttempt:       newMetricBind9ResolverValidationAttempt(mbc.Metrics.Bind9ResolverValidationAttempt),
		metricBind9ResolverValidationSuccess:       newMetricBind9ResolverValidationSuccess(mbc.Metrics.Bind9ResolverValidationSuccess),
		metricBind9ServerQueries:                   newMetricBind9ServerQueries(mbc.Metrics.Bind9ServerQueries),
		metricBind9ServerResponses:                 newMetricBind9ServerResponses(mbc.Metrics.Bind9ServerResponses),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricBind9MemoryTotal.emit(ils.Metrics())
	mb.metricBind9MemoryUsage.emit(ils.Metrics())
	mb.metricBind9NetworkSocketAccept.emit(ils.Metrics())
	mb.metricBind9NetworkSocketAcceptFailures.emit(ils.Metrics())
	mb.metricBind9NetworkSocketActive.emit(ils.Metrics())
	mb.metricBind9NetworkSocketBindFailures.emit(ils.Metrics())
	mb.metricBind9NetworkSocketClosed.emit(ils.Metrics())
	mb.metricBind9NetworkSocketConnection.emit(ils.Metrics())
	mb.metricBind9NetworkSocketConnectionFailures.emit(ils.Metrics())
	mb.metricBind9NetworkSocketOpenFailures.emit(ils.Metrics())
	mb.metricBind9NetworkSocketOpened.emit(ils.Metrics())
	mb.metricBind9NetworkSocketReceiveErrors.emit(ils.Metrics())
	mb.metricBind9NetworkSocketSendErrors.emit(ils.Metrics())
	mb.metricBind9NetworkTraffic.emit(ils.Metrics())
	mb.metricBind9ResolverCacheEntries.emit(ils.Metrics())
	mb.metricBind9ResolverCacheHits.emit(ils.Metrics())
	mb.metricBind9ResolverCacheMisses.emit(ils.Metrics())
	mb.metricBind9ResolverQueries.emit(ils.Metrics())
	mb.metricBind9ResolverResponses.emit(ils.Metrics())
	mb.metricBind9ResolverValidationAttempt.emit(ils.Metrics())
	mb.metricBind9ResolverValidationSuccess.emit(ils.Metrics())
	mb.metricBind9ServerQueries.emit(ils.Metrics())
	mb.metricBind9ServerResponses.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordBind9MemoryTotalDataPoint adds a data point to bind9.memory.total metric.
func (mb *MetricsBuilder) RecordBind9MemoryTotalDataPoint(ts pcommon.Timestamp, val int64, contextNameAttributeValue string) {
	mb.metricBind9MemoryTotal.recordDataPoint(mb.startTime, ts, val, contextNameAttributeValue)
}

// RecordBind9MemoryUsageDataPoint adds a data point to bind9.memory.usage metric.
func (mb *MetricsBuilder) RecordBind9MemoryUsageDataPoint(ts pcommon.Timestamp, val int64, contextNameAttributeValue string) {
	mb.metricBind9MemoryUsage.recordDataPoint(mb.startTime, ts, val, contextNameAttributeValue)
}

// RecordBind9NetworkSocketAcceptDataPoint adds a data point to bind9.network.socket.accept metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketAcceptDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketAccept.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketAcceptFailuresDataPoint adds a data point to bind9.network.socket.accept.failures metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketAcceptFailuresDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketAcceptFailures.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketActiveDataPoint adds a data point to bind9.network.socket.active metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketActiveDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketActive.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketBindFailuresDataPoint adds a data point to bind9.network.socket.bind.failures metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketBindFailuresDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketBindFailures.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketClosedDataPoint adds a data point to bind9.network.socket.closed metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketClosedDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketClosed.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketConnectionDataPoint adds a data point to bind9.network.socket.connection metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketConnectionDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketConnection.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketConnectionFailuresDataPoint adds a data point to bind9.network.socket.connection.failures metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketConnectionFailuresDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketConnectionFailures.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketOpenFailuresDataPoint adds a data point to bind9.network.socket.open.failures metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketOpenFailuresDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketOpenFailures.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketOpenedDataPoint adds a data point to bind9.network.socket.opened metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketOpenedDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketOpened.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketReceiveErrorsDataPoint adds a data point to bind9.network.socket.receive.errors metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketReceiveErrorsDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketReceiveErrors.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkSocketSendErrorsDataPoint adds a data point to bind9.network.socket.send.errors metric.
func (mb *MetricsBuilder) RecordBind9NetworkSocketSendErrorsDataPoint(ts pcommon.Timestamp, val int64, socketStatAttributeValue string) {
	mb.metricBind9NetworkSocketSendErrors.recordDataPoint(mb.startTime, ts, val, socketStatAttributeValue)
}

// RecordBind9NetworkTrafficDataPoint adds a data point to bind9.network.traffic metric.
func (mb *MetricsBuilder) RecordBind9NetworkTrafficDataPoint(ts pcommon.Timestamp, val int64, networkTransportAttributeValue AttributeNetworkTransport, networkTypeAttributeValue AttributeNetworkType, dnsMessageDirectionAttributeValue AttributeDNSMessageDirection, dnsMessageSizeBucketAttributeValue string) {
	mb.metricBind9NetworkTraffic.recordDataPoint(mb.startTime, ts, val, networkTransportAttributeValue.String(), networkTypeAttributeValue.String(), dnsMessageDirectionAttributeValue.String(), dnsMessageSizeBucketAttributeValue)
}

// RecordBind9ResolverCacheEntriesDataPoint adds a data point to bind9.resolver.cache.entries metric.
func (mb *MetricsBuilder) RecordBind9ResolverCacheEntriesDataPoint(ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	mb.metricBind9ResolverCacheEntries.recordDataPoint(mb.startTime, ts, val, viewAttributeValue)
}

// RecordBind9ResolverCacheHitsDataPoint adds a data point to bind9.resolver.cache.hits metric.
func (mb *MetricsBuilder) RecordBind9ResolverCacheHitsDataPoint(ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	mb.metricBind9ResolverCacheHits.recordDataPoint(mb.startTime, ts, val, viewAttributeValue)
}

// RecordBind9ResolverCacheMissesDataPoint adds a data point to bind9.resolver.cache.misses metric.
func (mb *MetricsBuilder) RecordBind9ResolverCacheMissesDataPoint(ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	mb.metricBind9ResolverCacheMisses.recordDataPoint(mb.startTime, ts, val, viewAttributeValue)
}

// RecordBind9ResolverQueriesDataPoint adds a data point to bind9.resolver.queries metric.
func (mb *MetricsBuilder) RecordBind9ResolverQueriesDataPoint(ts pcommon.Timestamp, val int64, viewAttributeValue string, qtypeAttributeValue string) {
	mb.metricBind9ResolverQueries.recordDataPoint(mb.startTime, ts, val, viewAttributeValue, qtypeAttributeValue)
}

// RecordBind9ResolverResponsesDataPoint adds a data point to bind9.resolver.responses metric.
func (mb *MetricsBuilder) RecordBind9ResolverResponsesDataPoint(ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	mb.metricBind9ResolverResponses.recordDataPoint(mb.startTime, ts, val, viewAttributeValue)
}

// RecordBind9ResolverValidationAttemptDataPoint adds a data point to bind9.resolver.validation.attempt metric.
func (mb *MetricsBuilder) RecordBind9ResolverValidationAttemptDataPoint(ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	mb.metricBind9ResolverValidationAttempt.recordDataPoint(mb.startTime, ts, val, viewAttributeValue)
}

// RecordBind9ResolverValidationSuccessDataPoint adds a data point to bind9.resolver.validation.success metric.
func (mb *MetricsBuilder) RecordBind9ResolverValidationSuccessDataPoint(ts pcommon.Timestamp, val int64, viewAttributeValue string) {
	mb.metricBind9ResolverValidationSuccess.recordDataPoint(mb.startTime, ts, val, viewAttributeValue)
}

// RecordBind9ServerQueriesDataPoint adds a data point to bind9.server.queries metric.
func (mb *MetricsBuilder) RecordBind9ServerQueriesDataPoint(ts pcommon.Timestamp, val int64, opcodeAttributeValue AttributeOpcode) {
	mb.metricBind9ServerQueries.recordDataPoint(mb.startTime, ts, val, opcodeAttributeValue.String())
}

// RecordBind9ServerResponsesDataPoint adds a data point to bind9.server.responses metric.
func (mb *MetricsBuilder) RecordBind9ServerResponsesDataPoint(ts pcommon.Timestamp, val int64, rcodeAttributeValue AttributeRcode) {
	mb.metricBind9ServerResponses.recordDataPoint(mb.startTime, ts, val, rcodeAttributeValue.String())
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
