// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9MemoryTotalDataPoint(ts, 1, "context.name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9MemoryUsageDataPoint(ts, 1, "context.name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketAcceptDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketAcceptFailuresDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketActiveDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketBindFailuresDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketClosedDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketConnectionDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketConnectionFailuresDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketOpenFailuresDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketOpenedDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketReceiveErrorsDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkSocketSendErrorsDataPoint(ts, 1, "socket.stat-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9NetworkTrafficDataPoint(ts, 1, AttributeNetworkTransportUdp, AttributeNetworkTypeIpv4, AttributeDNSMessageDirectionReceived, "dns.message.size.bucket-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9ResolverCacheEntriesDataPoint(ts, 1, "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9ResolverCacheHitsDataPoint(ts, 1, "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9ResolverCacheMissesDataPoint(ts, 1, "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9ResolverQueriesDataPoint(ts, 1, "view-val", "qtype-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9ResolverResponsesDataPoint(ts, 1, "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9ResolverValidationAttemptDataPoint(ts, 1, "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9ResolverValidationSuccessDataPoint(ts, 1, "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9ServerQueriesDataPoint(ts, 1, AttributeOpcodeQUERY)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBind9ServerResponsesDataPoint(ts, 1, AttributeRcodeNOERROR)

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "bind9.memory.total":
					assert.False(t, validatedMetrics["bind9.memory.total"], "Found a duplicate in the metrics slice: bind9.memory.total")
					validatedMetrics["bind9.memory.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Total memory allocated by context name", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					contextNameAttrVal, ok := dp.Attributes().Get("context.name")
					assert.True(t, ok)
					assert.Equal(t, "context.name-val", contextNameAttrVal.Str())
				case "bind9.memory.usage":
					assert.False(t, validatedMetrics["bind9.memory.usage"], "Found a duplicate in the metrics slice: bind9.memory.usage")
					validatedMetrics["bind9.memory.usage"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Memory usage by context name", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					contextNameAttrVal, ok := dp.Attributes().Get("context.name")
					assert.True(t, ok)
					assert.Equal(t, "context.name-val", contextNameAttrVal.Str())
				case "bind9.network.socket.accept":
					assert.False(t, validatedMetrics["bind9.network.socket.accept"], "Found a duplicate in the metrics slice: bind9.network.socket.accept")
					validatedMetrics["bind9.network.socket.accept"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of socket accept calls, by socket statistic name", mi.Description())
					assert.Equal(t, "sockets", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.accept.failures":
					assert.False(t, validatedMetrics["bind9.network.socket.accept.failures"], "Found a duplicate in the metrics slice: bind9.network.socket.accept.failures")
					validatedMetrics["bind9.network.socket.accept.failures"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of socket accept failures, by socket statistic name", mi.Description())
					assert.Equal(t, "failures", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.active":
					assert.False(t, validatedMetrics["bind9.network.socket.active"], "Found a duplicate in the metrics slice: bind9.network.socket.active")
					validatedMetrics["bind9.network.socket.active"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of currently active sockets, by socket statistic name", mi.Description())
					assert.Equal(t, "sockets", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.bind.failures":
					assert.False(t, validatedMetrics["bind9.network.socket.bind.failures"], "Found a duplicate in the metrics slice: bind9.network.socket.bind.failures")
					validatedMetrics["bind9.network.socket.bind.failures"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of socket bind failures, by socket statistic name", mi.Description())
					assert.Equal(t, "failures", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.closed":
					assert.False(t, validatedMetrics["bind9.network.socket.closed"], "Found a duplicate in the metrics slice: bind9.network.socket.closed")
					validatedMetrics["bind9.network.socket.closed"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of sockets closed, by socket statistic name", mi.Description())
					assert.Equal(t, "sockets", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.connection":
					assert.False(t, validatedMetrics["bind9.network.socket.connection"], "Found a duplicate in the metrics slice: bind9.network.socket.connection")
					validatedMetrics["bind9.network.socket.connection"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of socket connections established, by socket statistic name", mi.Description())
					assert.Equal(t, "sockets", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.connection.failures":
					assert.False(t, validatedMetrics["bind9.network.socket.connection.failures"], "Found a duplicate in the metrics slice: bind9.network.socket.connection.failures")
					validatedMetrics["bind9.network.socket.connection.failures"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of socket connection failures, by socket statistic name", mi.Description())
					assert.Equal(t, "failures", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.open.failures":
					assert.False(t, validatedMetrics["bind9.network.socket.open.failures"], "Found a duplicate in the metrics slice: bind9.network.socket.open.failures")
					validatedMetrics["bind9.network.socket.open.failures"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of socket open failures, by socket statistic name", mi.Description())
					assert.Equal(t, "failures", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.opened":
					assert.False(t, validatedMetrics["bind9.network.socket.opened"], "Found a duplicate in the metrics slice: bind9.network.socket.opened")
					validatedMetrics["bind9.network.socket.opened"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of sockets opened, by socket statistic name", mi.Description())
					assert.Equal(t, "sockets", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.receive.errors":
					assert.False(t, validatedMetrics["bind9.network.socket.receive.errors"], "Found a duplicate in the metrics slice: bind9.network.socket.receive.errors")
					validatedMetrics["bind9.network.socket.receive.errors"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of socket receive errors, by socket statistic name", mi.Description())
					assert.Equal(t, "errors", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.socket.send.errors":
					assert.False(t, validatedMetrics["bind9.network.socket.send.errors"], "Found a duplicate in the metrics slice: bind9.network.socket.send.errors")
					validatedMetrics["bind9.network.socket.send.errors"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of socket send errors, by socket statistic name", mi.Description())
					assert.Equal(t, "errors", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					socketStatAttrVal, ok := dp.Attributes().Get("socket.stat")
					assert.True(t, ok)
					assert.Equal(t, "socket.stat-val", socketStatAttrVal.Str())
				case "bind9.network.traffic":
					assert.False(t, validatedMetrics["bind9.network.traffic"], "Found a duplicate in the metrics slice: bind9.network.traffic")
					validatedMetrics["bind9.network.traffic"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "DNS message count by size bucket, protocol, direction, and IP version", mi.Description())
					assert.Equal(t, "messages", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					networkTransportAttrVal, ok := dp.Attributes().Get("network.transport")
					assert.True(t, ok)
					assert.Equal(t, "udp", networkTransportAttrVal.Str())
					networkTypeAttrVal, ok := dp.Attributes().Get("network.type")
					assert.True(t, ok)
					assert.Equal(t, "ipv4", networkTypeAttrVal.Str())
					dnsMessageDirectionAttrVal, ok := dp.Attributes().Get("dns.message.direction")
					assert.True(t, ok)
					assert.Equal(t, "received", dnsMessageDirectionAttrVal.Str())
					dnsMessageSizeBucketAttrVal, ok := dp.Attributes().Get("dns.message.size.bucket")
					assert.True(t, ok)
					assert.Equal(t, "dns.message.size.bucket-val", dnsMessageSizeBucketAttrVal.Str())
				case "bind9.resolver.cache.entries":
					assert.False(t, validatedMetrics["bind9.resolver.cache.entries"], "Found a duplicate in the metrics slice: bind9.resolver.cache.entries")
					validatedMetrics["bind9.resolver.cache.entries"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of entries in the resolver cache, by view", mi.Description())
					assert.Equal(t, "entries", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					viewAttrVal, ok := dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", viewAttrVal.Str())
				case "bind9.resolver.cache.hits":
					assert.False(t, validatedMetrics["bind9.resolver.cache.hits"], "Found a duplicate in the metrics slice: bind9.resolver.cache.hits")
					validatedMetrics["bind9.resolver.cache.hits"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cache hits in the resolver, by view", mi.Description())
					assert.Equal(t, "hits", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					viewAttrVal, ok := dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", viewAttrVal.Str())
				case "bind9.resolver.cache.misses":
					assert.False(t, validatedMetrics["bind9.resolver.cache.misses"], "Found a duplicate in the metrics slice: bind9.resolver.cache.misses")
					validatedMetrics["bind9.resolver.cache.misses"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cache misses in the resolver, by view", mi.Description())
					assert.Equal(t, "misses", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					viewAttrVal, ok := dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", viewAttrVal.Str())
				case "bind9.resolver.queries":
					assert.False(t, validatedMetrics["bind9.resolver.queries"], "Found a duplicate in the metrics slice: bind9.resolver.queries")
					validatedMetrics["bind9.resolver.queries"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of outgoing queries made by the resolver, by view and query type", mi.Description())
					assert.Equal(t, "queries", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					viewAttrVal, ok := dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", viewAttrVal.Str())
					qtypeAttrVal, ok := dp.Attributes().Get("qtype")
					assert.True(t, ok)
					assert.Equal(t, "qtype-val", qtypeAttrVal.Str())
				case "bind9.resolver.responses":
					assert.False(t, validatedMetrics["bind9.resolver.responses"], "Found a duplicate in the metrics slice: bind9.resolver.responses")
					validatedMetrics["bind9.resolver.responses"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of responses received by the resolver, by view", mi.Description())
					assert.Equal(t, "responses", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					viewAttrVal, ok := dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", viewAttrVal.Str())
				case "bind9.resolver.validation.attempt":
					assert.False(t, validatedMetrics["bind9.resolver.validation.attempt"], "Found a duplicate in the metrics slice: bind9.resolver.validation.attempt")
					validatedMetrics["bind9.resolver.validation.attempt"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of DNSSEC validation attempts by the resolver, by view", mi.Description())
					assert.Equal(t, "validations", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					viewAttrVal, ok := dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", viewAttrVal.Str())
				case "bind9.resolver.validation.success":
					assert.False(t, validatedMetrics["bind9.resolver.validation.success"], "Found a duplicate in the metrics slice: bind9.resolver.validation.success")
					validatedMetrics["bind9.resolver.validation.success"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of successful DNSSEC validations by the resolver, by view", mi.Description())
					assert.Equal(t, "validations", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					viewAttrVal, ok := dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", viewAttrVal.Str())
				case "bind9.server.queries":
					assert.False(t, validatedMetrics["bind9.server.queries"], "Found a duplicate in the metrics slice: bind9.server.queries")
					validatedMetrics["bind9.server.queries"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of queries received by the server, by opcode", mi.Description())
					assert.Equal(t, "queries", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					opcodeAttrVal, ok := dp.Attributes().Get("opcode")
					assert.True(t, ok)
					assert.Equal(t, "QUERY", opcodeAttrVal.Str())
				case "bind9.server.responses":
					assert.False(t, validatedMetrics["bind9.server.responses"], "Found a duplicate in the metrics slice: bind9.server.responses")
					validatedMetrics["bind9.server.responses"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of responses sent by the server, by rcode", mi.Description())
					assert.Equal(t, "responses", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					rcodeAttrVal, ok := dp.Attributes().Get("rcode")
					assert.True(t, ok)
					assert.Equal(t, "NOERROR", rcodeAttrVal.Str())
				}
			}
		})
	}
}
